---
title: "2_analyse_CCVR05"
author: "Tom Beesley"
date: "06/06/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

data <- read_csv("data_tidy_main_CCVR05.csv",
                 col_types = cols(gender = col_character()))

# get stats on % timeouts, % too many responses
trialsRemoved_Summary <- data %>% 
  group_by(p_num) %>% 
  summarise(perc_Timeout = (1-sum(camera_distance_from_target > 0)/n())*100, 
            respN_trials_Above_1 = sum(num_mistakes>max_Resp_allowed)/n()*100)

# Magda queried this - split timeouts and >1 resp calculations across near and far targets
data %>% 
  separate(set, into = c("TT", "Target_Depth")) %>% 
  group_by(p_num, Target_Depth) %>% 
  summarise(perc_Timeout = (1-sum(camera_distance_from_target > 0)/n())*100, 
            respN_trials_Above_1 = sum(num_mistakes>max_Resp_allowed)/n()*100) %>% 
  pivot_wider(names_from = Target_Depth, values_from = c(perc_Timeout, respN_trials_Above_1)) %>% 
  write_csv("removed_summary_by_Depth.csv")


# remove trials with too many responses and timeouts
data <- data %>% filter(camera_distance_from_target > 0,
                        num_mistakes <= max_Resp_allowed)

# get stats on meanRT, meanNResp, % trials analysed, join to the other stats
basic_stats_Summary <- data %>% 
  group_by(p_num) %>% 
  summarise(age = first(age),
            gender = first(gender),
            respN_mean = mean(num_mistakes),
            RT_mean = mean(response_time),
            perc_Analysed = (n()/288)*100) %>% 
  left_join(trialsRemoved_Summary, by = "p_num") # join the pre-filter stats


# separate into stage 1 and stage 2
data_stg1 <- data %>% 
  filter(block<=10)

# target switches were not coded in to the experiments
# so, this works out which trials in phase 2 had switched targets, based on p_num, set, and quadrant
data_stg2 <- data %>% 
  filter(block>10) %>% 
  mutate(switch_target = case_when(
    p_num%%2==1 & set=="rep_NT" & quadrant %in% c(1,3) ~ "S",
    p_num%%2==1 & set=="rep_NT" & quadrant %in% c(2,4) ~ "NS",
    p_num%%2==1 & set=="rep_FT" & quadrant %in% c(1,3) ~ "NS",
    p_num%%2==1 & set=="rep_FT" & quadrant %in% c(2,4) ~ "S",
    p_num%%2==0 & set=="rep_NT" & quadrant %in% c(1,3) ~ "NS",
    p_num%%2==0 & set=="rep_NT" & quadrant %in% c(2,4) ~ "S",
    p_num%%2==0 & set=="rep_FT" & quadrant %in% c(1,3) ~ "S",
    p_num%%2==0 & set=="rep_FT" & quadrant %in% c(2,4) ~ "NS",
    str_detect(set, "rand") ~ "NS"
    ))

# stage 1 summary data
stg1RT <- data_stg1 %>% 
  group_by(p_num, set, epoch) %>% 
  summarise(meanRT = mean(response_time)) %>% 
  arrange(p_num, desc(set)) %>% 
  pivot_wider(names_from = c("set", "epoch"), values_from = meanRT)

# stage 2 summary data
stg2RT <- data_stg2 %>% 
  group_by(p_num, set, ST = switch_target, epoch) %>% 
  summarise(meanRT = mean(response_time)) %>% 
  arrange(p_num, desc(set)) %>% 
  pivot_wider(names_from = c(set, ST, epoch), values_from = meanRT)

# stage 2 summary data
data_stg2 %>% 
  group_by(set, ST = switch_target) %>% 
  summarise(meanRT = mean(response_time)) %>% 
  ggplot(aes(x = ST, y = meanRT, fill = set)) +
  geom_col(position = position_dodge())


# awareness data
summaryAwareness <- dataAwareness %>% 
  group_by(p_num, set) %>% 
  summarise(meanChoice = mean(fc_response)) %>%
  arrange(p_num, desc(set)) %>% 
  pivot_wider(names_from = set, values_from = meanChoice) %>% 
  mutate(new_NT = 1-new_NT,
         new_FT = 1-new_FT)

# write output of all data to csv (for student)
left_join(basic_stats_Summary, stg1RT, by = "p_num") %>%
  left_join(., stg2RT, by = "p_num") %>% 
  left_join(., summaryAwareness, by = "p_num") %>% 
  write_csv("CCVR05_output.csv")


```

